[package]
name = "INWOX"
version = "0.1.0"
edition = "2021"
default-run = "INWOX"

[workspace]
members = ["kernel"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ovmf-prebuilt = "0.1.0-alpha.1"

[build-dependencies]
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }
bootloader = "0.11.7"
