[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kernel"
test = false
bench = false

[dependencies]
bootloader_api = "0.11.7"
embedded-graphics = "0.8.1"
spin = "0.9.8"
x86_64 = "0.15.1"
pic8259 = "0.11.0"
pc-keyboard = "0.7.0"
uart_16550 = "0.3.1"
linked_list_allocator = "0.10.5"
acpi = "5.0.0"
x2apic = "0.4.3"

[dependencies.lazy_static]
version = "1.5.0"
features = ["spin_no_std"]
